- src/components/StatusCard/components/Compact/index.tsx
- src/components/StatusCard/components/Compact/types.ts
- src/components/StatusCard/components/Standard/index.tsx
- src/components/StatusCard/components/Standard/types.ts
- src/components/StatusCard/stories.tsx
- src/components/StatusCard/types.ts
> renamed disabled/fill to isDisabled and isFilled

- src/components/StatusCard/__snapshots__/test.tsx.snap
- src/components/StatusCard/components/Compact/index.tsx
- src/components/StatusCard/components/Standard/index.tsx
- src/components/StatusCard/test.tsx
- theme/cerveza/src/components/_StatusCard.scss
> initial tests for status card

- src/components/Button/index.tsx
- src/components/Button/stories.tsx
- src/components/Button/types.ts
- theme/cerveza/src/_variables.scss
- theme/cerveza/src/components/_Button.scss
- Updated the `Button` component to use the `brew-` prefixed classes
- Created a "text" variant
- Updated the variables according to the design docs
> Updated button classes and styles

- package.json
- Updated the package.json scripts to break out the sass script and the storybook script, and combine them into `start`
> Package script changes

- src/utilities/ClickAwayListener/index.tsx
- src/utilities/ClickAwayListener/stories.tsx
- src/utilities/ClickAwayListener/types.ts
- Passed the click event through to the `onClickAway` function
- Changed the functionality to work with multiple children, as would be the case with a React.Fragment
> improvement(clickawaylistener): minor tweaks to ClickAwayHandler

- package-lock.json
- package.json
> Updated 'react-hook-form' to be a dependency

- src/components/Button/types.ts
- src/components/Form/components/FormField/index.tsx
- src/components/Form/components/FormSubmit/index.tsx
- src/components/Form/index.tsx
- src/components/Form/stories.tsx
- src/components/Input/components/TextField/index.tsx
Made a couple of small updates to improve how forms functioned.  Prior to these changes, I could not get `required` validation to show error messages.
> Updated forms to work with 'required' validation

- themes/cerveza/components/Typography.d.ts
- themes/cerveza/components/Typography.js
- themes/cerveza/components/Typography.ts
This pull request fixes the `body1` and `caption` according to the ProUI style guide.
> Typography fixes according to ProUI style guide

- src/components/FormField/index.tsx
> fixes #108

- .build/syncBranches.sh
- package-lock.json
- package.json
- src/components/FormField/types.ts
- src/components/FormSubmit/index.tsx
- themes/cerveza/components/Button.d.ts
- themes/cerveza/components/Button.js
- themes/cerveza/components/Button.ts
- themes/cerveza/index.d.ts
- themes/cerveza/index.js
- themes/cerveza/variables.js
- themes/cerveza/variables.ts
- themes/package.json
- themes/tsconfig.json
> Fixes issue #110

- src/components/FormField/index.tsx
- src/components/FormField/styles.ts
> fix: error msg shows w animation

- src/components/FormField/index.tsx
- src/components/FormField/stories.tsx
Fix the helper text overriting error message in FormField component on
Brewkit
✅ Closes: OVRC-12345
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the code style of this project.
> fix: 🐛 Brewkit fix the helper text issue

- .eslintrc.json
Disable max-lines-per-function, and limit max-statements to 100 and to throw an error
> chore: 🤖 Eslint rules stuff

- src/components/Button/index.tsx
- src/components/Button/stories.tsx
- src/components/Button/styles.ts
- src/components/TextField/index.tsx
- src/components/TextField/stories.tsx
- src/components/TextField/styles.ts
[OVRC-11935](https://jira.control4.com/browse/OVRC-11935)
[OVRC-11936](https://jira.control4.com/browse/OVRC-11936)
> Ovrc 11935 ovrc 11936 refactor button and text field components

- src/components/Button/styles.ts
- src/components/Button/types.ts
- src/components/Checkbox/styles.ts
- src/components/Checkbox/types.ts
- src/components/CircularProgress/types.ts
- src/components/TextField/styles.ts
- src/components/TextField/types.ts
- src/docs/BkOverrides.stories.mdx
- src/docs/GettingStarted.stories.mdx
- themes/cerveza-dark/index.js
- themes/cerveza-dark/index.ts
- themes/cerveza/index.js
- themes/cerveza/index.ts
- tsconfig.json
> refactor: 💡 Replace `createMuiTheme` with `createTheme`

- themes/cerveza-dark/components/InputLabel.js
- themes/cerveza-dark/components/InputLabel.ts
> fix: 🐛 Resolve dark mode color issue with Input Label

- .build/storybook/preview.js
> fix: 🐛 Remove unused files on startup

- src/components/FormField/index.tsx
Added missing ref to FormField
> fix: 🐛 Added ref to FormField

- .eslintrc.json
- src/components/FormField/index.tsx
> fix: 🐛 trying to resolve issues with FormField validation

- .eslintrc.json
- src/components/FormField/index.tsx
Reverts brewkit/components#151
> Revert "fix: 🐛 trying to resolve issues with FormField validation"

- .eslintrc.json
- src/components/FormField/index.tsx
- src/components/FormField/stories.tsx
- src/components/FormField/styles.ts
- src/components/FormSubmit/index.tsx
Reverts brewkit/components#159
> Revert "fix: 🐛 FormField validation"

- .gitignore
- themes/cerveza-dark/components/InputBase.ts
- themes/cerveza-dark/components/Select.ts
- themes/cerveza-dark/components/Typography.ts
- themes/cerveza-dark/index.ts
> added dark colors for some components

- .build/jest/bin/runner.js
- .build/jest/bin/setupTestEnv.js
- jest.config.js
- package.json
Fixed some test-runner cli bugs
> fix: 🐛 Fix some test-runner cli stuff

- package-lock.json
- src/components/Checkbox/Checkbox.spec.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/Checkbox.types.ts
- src/components/Checkbox/index.tsx
- src/components/Checkbox/stories.tsx
- src/components/FormField/FormField.tsx
- src/components/TextField/TextField.spec.tsx
- src/components/TextField/TextField.tsx
- src/components/TextField/TextField.types.ts
- src/components/TextField/index.tsx
- src/components/TextField/stories.tsx
- src/components/index.tsx
> OVRC-13101 Checkbox and TextField Tests

- themes/cerveza/components/Checkbox.js
- themes/cerveza/components/Checkbox.ts
border width changed from 2px to 1px to resolve polish bug 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
> Reduce border padding to match ovrc inputs

- src/components/ButtonGroup/stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/index.tsx
- src/components/Checkbox/stories.tsx
- src/components/Checkbox/styles.ts
- src/components/TextField/stories.tsx
> updating checkbox to have a sandbox

- src/components/Badge/Badge.spec.tsx
- src/components/Badge/Badge.story.tsx
- src/components/Badge/Badge.tsx
- src/components/Badge/Badge.types.ts
> Chore: Badge - Satisfy ESLint TS + Prettier Rules

- src/components/Alert/Alert.spec.tsx
- src/components/Alert/index.tsx
- src/components/Badge/Badge.story.tsx
- src/components/Badge/index.tsx
- src/components/Button/Button.spec.tsx
- src/components/Button/Button.story.tsx
- src/components/Button/Button.tsx
- src/components/Button/index.tsx
- src/components/Checkbox/Checkbox.spec.tsx
- src/components/Checkbox/index.tsx
- src/components/Form/Form.tsx
- src/components/Form/Form.types.ts
- src/components/Form/index.tsx
- src/components/SvgIcon/index.tsx
- src/components/TextField/TextField.spec.tsx
- src/components/TextField/index.tsx
> fix: 🐛 Resolve testing and storybook errors

- .github/workflows/ci.yml
Replaces https://github.com/brewkit/components/pull/211
> chore: 🤖 Add an initial small test cycle
